import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ExportCSVService {

  constructor() { }
  downloadCSV( data: any , fileName: string) {
    const blob = new Blob([data], { type: 'text/csv' });
        const url = window.URL.createObjectURL(blob);

        // 🔽 Création d'un lien invisible pour forcer le téléchargement
        const a = document.createElement('a');
        a.href = url;
        a.download = fileName;
        document.body.appendChild(a);
        a.click();

        // Nettoyage
        window.URL.revokeObjectURL(url);
        a.remove();
  }

  downloadPDF(data: any, fileName: string) {
  // If 'data' is a Blob or Uint8Array generated by pdfMake or similar
  const blob = new Blob([data], { type: 'application/pdf' });
  const url = window.URL.createObjectURL(blob);

  // 🔽 Create a hidden link to trigger download
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName.endsWith('.pdf') ? fileName : fileName + '.pdf';
  document.body.appendChild(a);
  a.click();

  // 🔽 Cleanup
  window.URL.revokeObjectURL(url);
  a.remove();
}
openPDF(data: any, fileName: string) {
  const blob = new Blob([data], { type: 'application/pdf' });
  const url = window.URL.createObjectURL(blob);

  // Open in a new tab
  const newWindow = window.open(url);
  if (newWindow) {
    newWindow.focus();
  } else {
    console.error('Popup blocked');
  }

  // Optional: revoke object URL after a delay
  setTimeout(() => {
    window.URL.revokeObjectURL(url);
  }, 10000); // 10s
}
openAndPrintPDF(data: any, fileName: string) {
  const blob = new Blob([data], { type: 'application/pdf' });
  const url = window.URL.createObjectURL(blob);

  // Open in a new tab
  const newWindow = window.open(url);
  if (newWindow) {
    // Wait for the PDF to load, then trigger print
    newWindow.onload = () => {
      newWindow.focus();
      newWindow.print();
    };
  } else {
    console.error('Popup blocked');
  }

  // Cleanup the object URL after a short delay
  setTimeout(() => {
    window.URL.revokeObjectURL(url);
  }, 10000); // 10 seconds
}

}
